ersion: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.19.1-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
    networks:
      - network

networks:
  network:
    driver: bridge